import { createHash, randomUUID } from 'node:crypto';
import * as path from 'node:path';
import { Effect, Option, Schema } from 'effect';
import { makeOutputBoundary } from './output-boundary.js';

/**
 * Archive resource classes with distinct cleanup and reporting semantics.
 */
export type ArchiveFileKind = 'page' | 'media';

/**
 * Immutable ownership record for one generated archive file.
 */
export interface ArchiveFile {
  /**
   * Portable path relative to the host archive root.
   */
  readonly path: string;

  /**
   * Whether the file contains normalized documentation or downloaded media.
   */
  readonly kind: ArchiveFileKind;

  /**
   * Source URL responsible for the file.
   */
  readonly url: string;

  /**
   * Digest of the bytes written by docsdown, used to protect local edits during cleanup.
   */
  readonly sha256: string;

  /**
   * Byte size at the time the file was generated.
   */
  readonly bytes: number;
}

/**
 * Searchable page entry included in every run manifest.
 */
export interface ManifestPage {
  /**
   * Canonical source URL.
   */
  readonly url: string;

  /**
   * Extracted or derived document title.
   */
  readonly title: string;
}

/**
 * Failed page, media, or transport operation that made a crawl partial.
 */
export interface ManifestFailure {
  /**
   * Resource that could not be archived.
   */
  readonly url: string;

  /**
   * Human-readable normalized failure reason.
   */
  readonly message: string;
}

/**
 * Complete crawl state required to finalize ownership and manifest history.
 */
export interface ManifestRun {
  /**
   * Provider adapter that produced this archive attempt.
   */
  readonly provider: string;

  /**
   * Normalized starting URL.
   */
  readonly source: string;

  /**
   * Path subtree that constrained link discovery.
   */
  readonly scopePath: string;

  /**
   * Exact path subtrees selected for this run.
   *
   * Website crawls contain the single link-discovery scope. GitHub crawls may contain several explicitly included
   * repository folders.
   */
  readonly scopePaths: ReadonlyArray<string>;

  /**
   * Number of page files generated in this attempt.
   */
  readonly pagesDownloaded: number;

  /**
   * Number of media files generated in this attempt.
   */
  readonly mediaDownloaded: number;

  /**
   * Search index entries for generated pages.
   */
  readonly pages: ReadonlyArray<ManifestPage>;

  /**
   * Acquisition counts keyed by document strategy.
   */
  readonly strategies: Readonly<Record<string, number>>;

  /**
   * Failures that suppress destructive cleanup and successful history snapshots.
   */
  readonly failures: ReadonlyArray<ManifestFailure>;

  /**
   * Files generated by this attempt, including content digests.
   */
  readonly files: ReadonlyArray<ArchiveFile>;

  /**
   * Whether queued pages remained after reaching the configured page limit.
   */
  readonly truncated: boolean;

  /**
   * Whether an otherwise successful crawl may remove stale owned files.
   */
  readonly cleanupEnabled: boolean;
}

/**
 * Cleanup and history outcome returned to the downloader and CLI.
 */
export interface ManifestResult {
  /**
   * `success` only when crawling and cleanup completed without failures.
   */
  readonly status: 'success' | 'partial';

  /**
   * Immutable successful-run snapshot, absent when the run was partial.
   */
  readonly historyPath: string | undefined;

  /**
   * Stale owned paths removed or already absent.
   */
  readonly removed: ReadonlyArray<string>;

  /**
   * Stale owned paths retained because their current digest differs from the recorded digest.
   */
  readonly preserved: ReadonlyArray<string>;

  /**
   * Filesystem errors encountered while inspecting or removing stale paths.
   */
  readonly cleanupFailures: ReadonlyArray<{ readonly path: string; readonly message: string }>;
}

/**
 * Ownership subset recovered from the previous latest-attempt manifest.
 */
interface PreviousManifest {
  /**
   * All files docsdown may consider for cleanup, including retained stale resources.
   */
  readonly ownedFiles: ReadonlyArray<ArchiveFile>;
}

/**
 * Exhaustive result of inspecting one stale ownership record.
 */
type CleanupResult =
  | { readonly state: 'removed'; readonly file: ArchiveFile }
  | { readonly state: 'preserved'; readonly file: ArchiveFile }
  | { readonly state: 'failed'; readonly file: ArchiveFile; readonly message: string };

/**
 * Stable filename for the latest-attempt manifest and ownership registry.
 */
const manifestFilename = 'manifest.json';

/**
 * Append-only directory containing snapshots of successful runs.
 */
const historyDirectoryName = '.manifests';

/**
 * Computes the content digest used to detect local changes before deletion.
 */
const digest = (content: string | Uint8Array): string => createHash('sha256').update(content).digest('hex');

/**
 * Measures strings as encoded UTF-8 and binary resources by their byte length.
 */
const byteLength = (content: string | Uint8Array): number =>
  typeof content === 'string' ? Buffer.byteLength(content) : content.byteLength;

/**
 * Converts an absolute generated path into the platform-independent form stored in manifests.
 */
const portableRelativePath = (rootDirectory: string, filePath: string): string =>
  path.relative(rootDirectory, filePath).split(path.sep).join('/');

/**
 * Rejects absolute, traversing, reserved, or non-canonical manifest paths before filesystem use.
 */
const isSafeArchivePath = (value: string): boolean => {
  if (!value || value.includes('\\') || path.posix.isAbsolute(value)) return false;
  const normalized = path.posix.normalize(value);
  if (normalized !== value || normalized === '.' || normalized === '..' || normalized.startsWith('../')) return false;
  const firstSegment = normalized.split('/')[0];
  return normalized !== manifestFilename && firstSegment !== historyDirectoryName;
};

/**
 * Digest-bearing ownership record accepted from an untrusted manifest.
 */
const ArchiveFileSchema = Schema.Struct({
  path: Schema.String.check(Schema.makeFilter(isSafeArchivePath)),
  kind: Schema.Literals(['page', 'media']),
  url: Schema.String,
  sha256: Schema.String.check(Schema.makeFilter((value) => /^[a-f0-9]{64}$/.test(value))),
  bytes: Schema.Number,
});

/**
 * Current, legacy, and schema-less manifest shapes decoded from JSON.
 *
 * Union order preserves the current `ownedFiles` field's precedence over the legacy `files` field.
 */
const PreviousManifestSchema = Schema.fromJsonString(
  Schema.Union([
    Schema.Struct({ ownedFiles: Schema.Array(Schema.Unknown) }),
    Schema.Struct({ files: Schema.Array(Schema.Unknown) }),
    Schema.Struct({}),
  ])
);

/**
 * Safely decodes the JSON boundary without throwing for malformed manifests.
 */
const decodePreviousManifest = Schema.decodeUnknownOption(PreviousManifestSchema);

/**
 * Safely decodes one ownership record so invalid siblings can be ignored independently.
 */
const decodeArchiveFile = Schema.decodeUnknownOption(ArchiveFileSchema);

/**
 * Filters unsafe ownership records, resolves duplicate paths by last value, and sorts deterministically.
 */
const normalizedFiles = (files: ReadonlyArray<ArchiveFile>): Array<ArchiveFile> => {
  const byPath = new Map<string, ArchiveFile>();
  for (const file of files) {
    if (isSafeArchivePath(file.path)) byPath.set(file.path, file);
  }
  return [...byPath.values()].sort((left, right) => left.path.localeCompare(right.path));
};

/**
 * Recovers owned files from current manifests and schema-compatible historical `files` arrays.
 *
 * Invalid or pre-digest records are ignored so legacy metadata can never authorize deletion.
 */
const parsePreviousManifest = (source: string): PreviousManifest | undefined => {
  const manifest = Option.getOrUndefined(decodePreviousManifest(source));
  if (!manifest) return undefined;
  const owned = 'ownedFiles' in manifest ? manifest.ownedFiles : 'files' in manifest ? manifest.files : [];
  return {
    ownedFiles: owned.flatMap((file) => {
      const parsed = Option.getOrUndefined(decodeArchiveFile(file));
      return parsed ? [parsed] : [];
    }),
  };
};

/**
 * Normalizes unknown filesystem failures for durable manifest reporting.
 */
const errorMessage = (error: { readonly message: string }): string => error.message;

/**
 * Unions ownership sets by portable path while preserving the newest record for duplicates.
 */
const mergeOwnedFiles = (...sets: ReadonlyArray<ReadonlyArray<ArchiveFile>>): Array<ArchiveFile> =>
  normalizedFiles(sets.flat());

/**
 * Describes a generated archive file so later runs can verify ownership before removing it.
 */
export const describeArchiveFile = (
  rootDirectory: string,
  filePath: string,
  kind: ArchiveFileKind,
  url: string,
  content: string | Uint8Array
): ArchiveFile => ({
  path: portableRelativePath(rootDirectory, filePath),
  kind,
  url,
  sha256: digest(content),
  bytes: byteLength(content),
});

/**
 * Writes the latest manifest, snapshots successful runs, and safely removes stale tool-owned files.
 */
export const finalizeManifest = (rootDirectory: string, run: ManifestRun) =>
  Effect.gen(function* () {
    const outputBoundary = yield* makeOutputBoundary(rootDirectory);
    const currentFiles = normalizedFiles(run.files);
    const previous = yield* outputBoundary.readFileString(path.join(rootDirectory, manifestFilename)).pipe(
      Effect.map(parsePreviousManifest),
      Effect.catch(() => Effect.succeed(undefined))
    );
    const previousOwned = normalizedFiles(previous?.ownedFiles ?? []);
    const currentPaths = new Set(currentFiles.map((file) => file.path));
    const staleFiles = previousOwned.filter((file) => !currentPaths.has(file.path));
    const crawlSucceeded = run.failures.length === 0 && !run.truncated;
    const cleanupEligible = crawlSucceeded && run.cleanupEnabled;

    const cleanupResults = cleanupEligible
      ? yield* Effect.forEach(
          staleFiles,
          (file): Effect.Effect<CleanupResult, never> =>
            Effect.gen(function* () {
              const destination = path.resolve(rootDirectory, ...file.path.split('/'));
              const exists = yield* outputBoundary.exists(destination);
              if (!exists) return { state: 'removed', file } as const;
              const content = yield* outputBoundary.readFile(destination);
              if (digest(content) !== file.sha256) return { state: 'preserved', file } as const;
              yield* outputBoundary.removeFile(destination);
              return { state: 'removed', file } as const;
            }).pipe(
              Effect.catch((error) =>
                Effect.succeed({ state: 'failed', file, message: errorMessage(error) } satisfies CleanupResult)
              )
            ),
          { concurrency: 1 }
        )
      : [];

    const removed = cleanupResults.filter((result) => result.state === 'removed').map((result) => result.file.path);
    const preservedFiles = cleanupResults.filter((result) => result.state === 'preserved').map((result) => result.file);
    const cleanupFailures = cleanupResults
      .filter((result): result is Extract<CleanupResult, { state: 'failed' }> => result.state === 'failed')
      .map((result) => ({ path: result.file.path, message: result.message }));
    const failedFiles = cleanupResults
      .filter((result): result is Extract<CleanupResult, { state: 'failed' }> => result.state === 'failed')
      .map((result) => result.file);
    const ownedFiles = cleanupEligible
      ? mergeOwnedFiles(currentFiles, preservedFiles, failedFiles)
      : mergeOwnedFiles(previousOwned, currentFiles);
    const status = crawlSucceeded && cleanupFailures.length === 0 ? ('success' as const) : ('partial' as const);
    const downloadedAt = new Date().toISOString();
    const runId = `${downloadedAt.replaceAll(':', '-')}-${randomUUID().slice(0, 8)}`;
    const manifest = {
      schemaVersion: 1,
      runId,
      status,
      provider: run.provider,
      source: run.source,
      scopePath: run.scopePath,
      scopePaths: run.scopePaths,
      downloadedAt,
      pagesDownloaded: run.pagesDownloaded,
      mediaDownloaded: run.mediaDownloaded,
      pages: [...run.pages].sort((left, right) => left.url.localeCompare(right.url)),
      strategies: run.strategies,
      failures: run.failures,
      truncated: run.truncated,
      files: currentFiles,
      ownedFiles,
      cleanup: {
        enabled: run.cleanupEnabled,
        eligible: cleanupEligible,
        removed,
        preserved: preservedFiles.map((file) => file.path),
        failures: cleanupFailures,
      },
    };
    const serialized = `${JSON.stringify(manifest, null, 2)}\n`;
    yield* outputBoundary.writeFile(path.join(rootDirectory, manifestFilename), serialized);

    let historyPath: string | undefined;
    if (status === 'success') {
      const historyDirectory = path.join(rootDirectory, historyDirectoryName);
      historyPath = path.join(historyDirectory, `${runId}.json`);
      yield* outputBoundary.writeFile(historyPath, serialized);
    }

    return {
      status,
      historyPath,
      removed,
      preserved: preservedFiles.map((file) => file.path),
      cleanupFailures,
    } satisfies ManifestResult;
  });
